#!/bin/bash

# Autostart Apps
#sxhkd -c ~/.config/openbox/sxhkdrc
xset +fp ~/.fonts/misc/
xset b off
xset r rate 250 25
xbacklight -set 5
#/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
redshift &
pcmanfm -d &
picom -b
dunst&

# Panel
tint2 &
#Wallpaper
nitrogen --restore &

